In [2]:
import IPython.display as ipd
import glob
from scipy.io import wavfile
import numpy as np
import pandas as pd
import librosa
import librosa.display
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib as plt
import matplotlib.pyplot as plt
import struct
from scipy.io import wavfile as wav
import os
from datetime import datetime 
from sklearn import metrics 
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, Conv2D, MaxPooling2D, GlobalAveragePooling2D
from keras.optimizers import Adam
from keras.utils import np_utils, to_categorical
from keras.callbacks import ModelCheckpoint 

In [4]:
def extract_features(file_name):
    nmfcc=40
    hop_length = 512
    n_fft = 1024
    n_mels = 128
    try:
        y, sr = librosa.load(file_name, res_type='kaiser_fast') 
        audio, _ = librosa.effects.trim(y)
        S = librosa.feature.mfcc(audio, sr=sr, n_fft=n_fft, hop_length=hop_length, center=False, n_mfcc=nmfcc, fmin=0)
        S_DB = librosa.power_to_db(S, ref=np.max)
        mfccsscaled = np.mean(S_DB.T,axis=0)   
    except Exception:
        print("Error encountered while parsing file: ", file_name)
        return None 
    return mfccsscaled

In [16]:
## Label filepath
fulldatasetpath = 'Audio_set/'
metadata = pd.read_csv('metadata/UrbanSound8k.csv')

## Check for audio in labels and get features
features = []
for index, row in metadata.iterrows():
    file_name = os.path.join(os.path.abspath(fulldatasetpath),str(row["slice_file_name"]))
    class_label = row["classID"]
    data = extract_features(file_name)
    features.append([data, class_label])
    
## Convert to pandas dataframe
featuresdf = pd.DataFrame(features, columns=['feature','class_label'])
featuresdf

                                                feature  class_label
0     [-80.0, -2.5677357, -80.0, -80.0, -80.0, -80.0...            3
1     [-80.0, -1.000009, -80.0, -3.5282154, -51.5522...            2
2     [-80.0, -0.9102828, -80.0, -4.7280188, -51.951...            2
3     [-80.0, -1.4973112, -77.357445, -4.4096923, -4...            2
4     [-80.0, -0.58883995, -80.0, -3.3096602, -45.63...            2
...                                                 ...          ...
8727  [-80.0, -0.64906764, -80.0, -6.3651896, -75.83...            1
8728  [-80.0, -2.813218, -80.0, -4.689935, -80.0, -5...            1
8729  [-80.0, -1.5988646, -80.0, -6.2588015, -74.091...            1
8730  [-80.0, -0.66870856, -80.0, -6.298651, -80.0, ...            1
8731  [-80.0, -1.0094088, -80.0, -4.0532303, -72.861...            1

[8732 rows x 2 columns]


In [17]:
class MultiHeadSelfAttention(layers.Layer):
    def __init__(self, embed_dim, num_heads=6):
        super(MultiHeadSelfAttention, self).__init__()
        self.embed_dim = embed_dim
        self.num_heads = num_heads
        if embed_dim % num_heads != 0:
            raise ValueError(
                f"embedding dimension = {embed_dim} should be divisible by number of heads = {num_heads}"
            )
        self.projection_dim = embed_dim // num_heads
        self.query_dense = layers.Dense(embed_dim)
        self.key_dense = layers.Dense(embed_dim)
        self.value_dense = layers.Dense(embed_dim)
        self.combine_heads = layers.Dense(embed_dim)

    def attention(self, query, key, value):
        score = tf.matmul(query, key, transpose_b=True)
        dim_key = tf.cast(tf.shape(key)[-1], tf.float32)
        scaled_score = score / tf.math.sqrt(dim_key)
        weights = tf.nn.softmax(scaled_score, axis=-1)
        output = tf.matmul(weights, value)
        return output, weights

    def separate_heads(self, x, batch_size):
        x = tf.reshape(x, (batch_size, -1, self.num_heads, self.projection_dim))
        return tf.transpose(x, perm=[0, 2, 1, 3])

    def call(self, inputs):
        ## x.shape = [batch_size, seq_len, embedding_dim]
        batch_size = tf.shape(inputs)[0]
        query = self.query_dense(inputs)
        
        ## (batch_size, seq_len, embed_dim)
        key = self.key_dense(inputs) 
        
        ## (batch_size, seq_len, embed_dim)
        value = self.value_dense(inputs) 
        
        ## (batch_size, seq_len, embed_dim)
        query = self.separate_heads(
            query, batch_size
        )  
        ## (batch_size, num_heads, seq_len, projection_dim)
        key = self.separate_heads(
            key, batch_size
        )  
        ## (batch_size, num_heads, seq_len, projection_dim)
        value = self.separate_heads(
            value, batch_size
        )  
        ## (batch_size, num_heads, seq_len, projection_dim)
        attention, weights = self.attention(query, key, value)
        attention = tf.transpose(
            attention, perm=[0, 2, 1, 3]
        )  
        ## (batch_size, seq_len, num_heads, projection_dim)
        concat_attention = tf.reshape(
            attention, (batch_size, -1, self.embed_dim)
        )  
        ## (batch_size, seq_len, embed_dim)
        output = self.combine_heads(
            concat_attention
        )  
        ## (batch_size, seq_len, embed_dim)
        return output

In [18]:
class TransformerBlock(layers.Layer):
    ## For calling multihead attention on embedded data and arranging it sequentially and adding other layers.
    def __init__(self, embed_dim, num_heads, ff_dim, rate=0.1):
        super(TransformerBlock, self).__init__()
        self.att = MultiHeadSelfAttention(embed_dim, num_heads)
        self.ffn = keras.Sequential(
            [layers.Dense(ff_dim, activation="relu"), layers.Dense(embed_dim),]
        )
        self.layernorm1 = layers.LayerNormalization(epsilon=1e-6)
        self.layernorm2 = layers.LayerNormalization(epsilon=1e-6)
        self.dropout1 = layers.Dropout(rate)
        self.dropout2 = layers.Dropout(rate)
        
    def call(self, inputs, training):
        attn_output = self.att(inputs)
        attn_output = self.dropout1(attn_output, training=training)
        out1 = self.layernorm1(inputs + attn_output)
        ffn_output = self.ffn(out1)
        ffn_output = self.dropout2(ffn_output, training=training)
        return self.layernorm2(out1 + ffn_output)

In [19]:
class TokenAndPositionEmbedding(layers.Layer):
    ## For preliminary token generation and embedding
    def __init__(self, maxlen, vocab_size, embed_dim):
        super(TokenAndPositionEmbedding, self).__init__()
        self.token_emb = layers.Embedding(input_dim=vocab_size, output_dim=embed_dim)
        self.pos_emb = layers.Embedding(input_dim=maxlen, output_dim=embed_dim)

    def call(self, x):
        maxlen = tf.shape(x)[-1]
        positions = tf.range(start=0, limit=maxlen, delta=1)
        positions = self.pos_emb(positions)
        x = self.token_emb(x)
        return x + positions

In [20]:
## Generating audio data in the word domain to apply transformer
featuresdf=featuresdf.dropna(axis=0)
print(featuresdf)
X = np.array(featuresdf.feature.tolist())
X=X*100000
min_X=-min([min(element) for element in X])
x=X+min_X
x=x.astype(int)
max_len=max([max(element) for element in x])
print(max_len)
# Getting label size
y = np.array(featuresdf.class_label.tolist())
print(x,x.shape)
print(y,y.shape)

                                                feature  class_label
0     [-80.0, -2.5677357, -80.0, -80.0, -80.0, -80.0...            3
1     [-80.0, -1.000009, -80.0, -3.5282154, -51.5522...            2
2     [-80.0, -0.9102828, -80.0, -4.7280188, -51.951...            2
3     [-80.0, -1.4973112, -77.357445, -4.4096923, -4...            2
4     [-80.0, -0.58883995, -80.0, -3.3096602, -45.63...            2
...                                                 ...          ...
8727  [-80.0, -0.64906764, -80.0, -6.3651896, -75.83...            1
8728  [-80.0, -2.813218, -80.0, -4.689935, -80.0, -5...            1
8729  [-80.0, -1.5988646, -80.0, -6.2588015, -74.091...            1
8730  [-80.0, -0.66870856, -80.0, -6.298651, -80.0, ...            1
8731  [-80.0, -1.0094088, -80.0, -4.0532303, -72.861...            1

[8732 rows x 2 columns]
8000000
[[      0 7743226       0 ... 2573972 2629853 3770590]
 [      0 7899999       0 ... 3708962 2854796 3255666]
 [      0 7908971       0 ...

In [21]:
from sklearn.model_selection import train_test_split 
#x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1,shuffle=False)
m,n=x.shape
print(m,n)
print(y.shape)
x_train=x[0:int(m*9/10),:]
x_test=x[int(m*9/10):m,:]
y_train=y[0:int(m*9/10)]
y_test=y[int(m*9/10):m]

8732 40
(8732,)


In [11]:
## Changing data type for transformer layers
m,n=x_test.shape
print(m,n)

## Converting form and reshaping
TestX=x_test
TestY=y_test
testy=np.reshape(TestY,(m,))

## Changing datatypes
testx=np.empty((m,),object)
for i in range (0,m):
    testx[i]=list(int(v) for v in TestX[i])
    testy[i]=testy[i].astype(int)

## Printing data-types - relevant to transformer input
print(type(testx))
print(type(testx[m-1][n-1]))
print(type(testx[m-1]))
print(type(testy[m-1]))
print(type(testy))

## Converting Train Data and Getting size of data
m,n=x_train.shape
print(m,n)

## Converting form and reshaping
TrainX=x_train
TrainY=y_train
trainy=np.reshape(TrainY,(m,))

## Changing datatypes
trainx=np.empty((m,),object)
for i in range (0,m):
    trainx[i]=list(int(v) for v in TrainX[i])
    trainy[i]=TrainY[i].astype(int)
    
## Printing data-types - relevant to transformer input
print(type(trainx))
print(type(trainx[m-1][n-1]))
print(type(trainx[m-1]))
print(type(trainy[m-1]))
print(type(trainy))
print(trainx.shape,trainy.shape,testx.shape,testy.shape)

874 40
<class 'numpy.ndarray'>
<class 'int'>
<class 'list'>
<class 'numpy.int32'>
<class 'numpy.ndarray'>
7858 40
<class 'numpy.ndarray'>
<class 'int'>
<class 'list'>
<class 'numpy.int32'>
<class 'numpy.ndarray'>
(7858,) (7858,) (874,) (874,)


In [12]:
vocab_size = max_len+1
maxlen = 40
print(len(trainx), "Training sequences")
print(len(testx), "Validation sequences")

## Converting to padded tensor sequence
trainx = keras.preprocessing.sequence.pad_sequences(trainx,maxlen=maxlen)
testx = keras.preprocessing.sequence.pad_sequences(testx,maxlen=maxlen)
print(trainx.shape,trainy.shape,testx.shape,testy.shape)
print(trainx,trainy,testx,testy)

7858 Training sequences
874 Validation sequences
(7858, 40) (7858,) (874, 40) (874,)
[[      0 7743226       0 ... 2573972 2629853 3770590]
 [      0 7899999       0 ... 3708962 2854796 3255666]
 [      0 7908971       0 ... 3848537 3874896 2767926]
 ...
 [      0 7853487       0 ... 4667272 2068970 3188562]
 [      0 7759655       0 ... 5486369 3050592 3924683]
 [      0 7792581       0 ... 5073622 3182251 5185436]] [3 2 2 ... 4 4 4] [[      0 7886826  110820 ... 2201447 5018277 4557853]
 [      0 7911832       0 ... 2387120 3787225 3220354]
 [      0 7902066   32901 ... 3111667 4550398 2754965]
 ...
 [      0 7840113       0 ... 2173984 4407086 5151892]
 [      0 7933129       0 ...  333429 2475616 5325988]
 [      0 7899059       0 ... 3489432   56613  933560]] [3 3 3 4 4 4 4 4 4 4 8 8 8 8 8 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 6 6 6 6 6 6 6 6 6 6 6 6 6 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 9 9


In [14]:
embed_dim = 30  ## Embedding size for each token
num_heads = 6  ## Number of attention heads
ff_dim = 30  ## Hidden layer size in feed forward network inside transformer

## Tokenizing input data with max dimension and embedding it
inputs = layers.Input(shape=(maxlen,))
#x = keras.Sequential()
embedding_layer = TokenAndPositionEmbedding(maxlen, vocab_size, embed_dim)
x = embedding_layer(inputs)

## Adding Sequential layer to the embedded data and attention layers too.
transformer_block = TransformerBlock(embed_dim, num_heads, ff_dim)
x = transformer_block(x)

## Add other layers
x = layers.Conv1D(6,3,padding="same")(x)
x = layers.Dense(30, activation="relu")(x)
x = layers.Dropout(0.5)(x)
x = layers.MaxPool1D(pool_size=2, strides=2)(x)
x = layers.Dense(30, activation="relu")(x)
x = layers.Dropout(0.5)(x)
x = layers.GlobalAveragePooling1D()(x)
x = layers.Dense(30, activation="relu")(x)
x = layers.Dropout(0.5)(x)
x = layers.Flatten()(x)
x = layers.Dense(30, activation="relu")(x)
x = layers.Dropout(0.5)(x)
x = layers.Dense(30, activation="relu")(x)
x = layers.Dropout(0.5)(x)

## Producing general softmax layer for classification
outputs = layers.Dense(10, activation="softmax")(x)

## Generating model
model = keras.Model(inputs=inputs, outputs=outputs)
model.summary()

Model: "functional_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 40)]              0         
_________________________________________________________________
token_and_position_embedding (None, 40, 30)            240001230 
_________________________________________________________________
transformer_block_1 (Transfo (None, 40, 30)            5700      
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 40, 6)             546       
_________________________________________________________________
dense_18 (Dense)             (None, 40, 30)            210       
_________________________________________________________________
dropout_9 (Dropout)          (None, 40, 30)            0         
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 20, 30)           

In [15]:
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
history = model.fit(trainx, trainy, batch_size=100, epochs=5)

Epoch 1/5
79/79 [==============================] - 162s 2s/step - loss: 2.3054 - accuracy: 0.1089
Epoch 2/5
79/79 [==============================] - 163s 2s/step - loss: 2.2808 - accuracy: 0.1121
Epoch 3/5
 7/79 [=>............................] - ETA: 2:17 - loss: 2.2819 - accuracy: 0.1057

KeyboardInterrupt: 

In [39]:
score = model.evaluate(trainx, trainy, verbose=0)
print("Training Performance",score)
score = model.evaluate(testx, testy, verbose=0)
print("Testing Performanr",score)

Training Performance [0.48297321796417236, 0.8677664995193481]
Testing Performanr [0.6155197620391846, 0.8627991080284119]


In [57]:
del model
keras.backend.clear_session()